# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 设置 JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: 构建
      run: mvn clean package

    - name: 上传工件
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "Chat2QQ-Bukkit.jar"
        path: target/Chat2QQ-Bukkit.jar
